import { useState } from "react";
import Shop from "./Shop";
import DialogCoupons from "../../../Dialogs/DialogCoupons/DialogCoupons";
import "./Shops.css";
import coupons from "../../../../data/coupons";
//"Logotypy prezentowane na stronie są własnością odpowiednich firm i zostały użyte wyłącznie w celu prezentacji ich ofert promocyjnych."

const lidlAllCoupons = [
  {
    name: "Nestl\u00e9 Fitness 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 6.06,
    price_after_discount: 3.94,
    expiration_date: "2025-02-14",
    category: "dry products",
  },
  {
    name: "Nescaf\u00e9 Classic 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 13.92,
    price_after_discount: 12.39,
    expiration_date: "2025-02-18",
    category: "water and drinks",
  },
  {
    name: "Oasis Orange Juice 500g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 5.39,
    price_after_discount: 4.58,
    expiration_date: "2025-02-02",
    category: "water and drinks",
  },
  {
    name: "Cheetos Puffs 120g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 6.69,
    price_after_discount: 5.75,
    expiration_date: "2025-01-20",
    category: "snacks and sweets",
  },
  {
    name: "Rama Margarine 500g",
    manufacturer: "Upfield",
    store: "Lidl",
    price_before_discount: 15.98,
    price_after_discount: 8.63,
    expiration_date: "2025-02-03",
    category: "dairy products",
  },
  {
    name: "Heinz Tomato Ketchup 500g",
    manufacturer: "Heinz",
    store: "Lidl",
    price_before_discount: 18.27,
    price_after_discount: 14.8,
    expiration_date: "2025-02-01",
    category: "spices and seasonings",
  },
  {
    name: "Nescaf\u00e9 Classic 120g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 5.33,
    price_after_discount: 3.2,
    expiration_date: "2025-02-08",
    category: "water and drinks",
  },
  {
    name: "Nestl\u00e9 Fitness 120g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 15.9,
    price_after_discount: 12.08,
    expiration_date: "2025-01-10",
    category: "dry products",
  },
  {
    name: "Lay's Classic Chips 120g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 7.65,
    price_after_discount: 6.2,
    expiration_date: "2025-02-07",
    category: "snacks and sweets",
  },
  {
    name: "Cheetos Puffs 250g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 16.7,
    price_after_discount: 11.19,
    expiration_date: "2025-01-19",
    category: "snacks and sweets",
  },
  {
    name: "Lipton Yellow Label Tea 120g",
    manufacturer: "Unilever",
    store: "Lidl",
    price_before_discount: 7.23,
    price_after_discount: 3.62,
    expiration_date: "2025-01-02",
    category: "water and drinks",
  },
  {
    name: "Rama Margarine 1000g",
    manufacturer: "Upfield",
    store: "Lidl",
    price_before_discount: 7.61,
    price_after_discount: 4.41,
    expiration_date: "2025-02-11",
    category: "dairy products",
  },
  {
    name: "Lipton Yellow Label Tea 250g",
    manufacturer: "Unilever",
    store: "Lidl",
    price_before_discount: 5.99,
    price_after_discount: 4.01,
    expiration_date: "2025-01-21",
    category: "water and drinks",
  },
  {
    name: "Nescaf\u00e9 Classic 500g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 12.18,
    price_after_discount: 6.94,
    expiration_date: "2025-01-04",
    category: "water and drinks",
  },
  {
    name: "Rama Margarine 120g",
    manufacturer: "Upfield",
    store: "Lidl",
    price_before_discount: 11.34,
    price_after_discount: 7.14,
    expiration_date: "2025-01-27",
    category: "dairy products",
  },
  {
    name: "Activia Yogurt 500g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 16.7,
    price_after_discount: 10.52,
    expiration_date: "2025-01-04",
    category: "dairy products",
  },
  {
    name: "Cheetos Puffs 1000g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 16.18,
    price_after_discount: 14.24,
    expiration_date: "2025-01-07",
    category: "snacks and sweets",
  },
  {
    name: "Nestl\u00e9 Fitness 250g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 3.8,
    price_after_discount: 3.0,
    expiration_date: "2025-02-17",
    category: "dry products",
  },
  {
    name: "Heinz Tomato Ketchup 250g",
    manufacturer: "Heinz",
    store: "Lidl",
    price_before_discount: 5.16,
    price_after_discount: 4.23,
    expiration_date: "2025-01-13",
    category: "spices and seasonings",
  },
  {
    name: "Heinz Tomato Ketchup 120g",
    manufacturer: "Heinz",
    store: "Lidl",
    price_before_discount: 4.38,
    price_after_discount: 2.89,
    expiration_date: "2025-01-13",
    category: "spices and seasonings",
  },
  {
    name: "Nestl\u00e9 Fitness 500g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 19.37,
    price_after_discount: 12.98,
    expiration_date: "2025-01-27",
    category: "dry products",
  },
  {
    name: "Activia Yogurt 120g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 3.4,
    price_after_discount: 2.65,
    expiration_date: "2025-01-12",
    category: "dairy products",
  },
  {
    name: "Rama Margarine 250g",
    manufacturer: "Upfield",
    store: "Lidl",
    price_before_discount: 9.15,
    price_after_discount: 7.5,
    expiration_date: "2025-01-20",
    category: "dairy products",
  },
  {
    name: "Oasis Orange Juice 250g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 17.26,
    price_after_discount: 14.33,
    expiration_date: "2025-02-01",
    category: "water and drinks",
  },
  {
    name: "Lay's Classic Chips 1000g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 16.85,
    price_after_discount: 11.12,
    expiration_date: "2025-01-31",
    category: "snacks and sweets",
  },
  {
    name: "Milka Chocolate Bar 500g",
    manufacturer: "Mondelez",
    store: "Lidl",
    price_before_discount: 4.04,
    price_after_discount: 2.95,
    expiration_date: "2025-02-16",
    category: "snacks and sweets",
  },
  {
    name: "Cheetos Puffs 500g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 7.29,
    price_after_discount: 5.9,
    expiration_date: "2025-01-24",
    category: "snacks and sweets",
  },
  {
    name: "Activia Yogurt 1000g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 16.95,
    price_after_discount: 8.98,
    expiration_date: "2025-01-09",
    category: "dairy products",
  },
  {
    name: "Lipton Yellow Label Tea 1000g",
    manufacturer: "Unilever",
    store: "Lidl",
    price_before_discount: 15.05,
    price_after_discount: 9.03,
    expiration_date: "2025-01-04",
    category: "water and drinks",
  },
  {
    name: "Oasis Orange Juice 1000g",
    manufacturer: "Danone",
    store: "Lidl",
    price_before_discount: 13.06,
    price_after_discount: 11.36,
    expiration_date: "2025-02-10",
    category: "water and drinks",
  },
  {
    name: "Milka Chocolate Bar 120g",
    manufacturer: "Mondelez",
    store: "Lidl",
    price_before_discount: 4.67,
    price_after_discount: 3.78,
    expiration_date: "2025-02-04",
    category: "snacks and sweets",
  },
  {
    name: "Lay's Classic Chips 500g",
    manufacturer: "Frito-Lay",
    store: "Lidl",
    price_before_discount: 19.38,
    price_after_discount: 9.69,
    expiration_date: "2025-02-09",
    category: "snacks and sweets",
  },
  {
    name: "Nescaf\u00e9 Classic 250g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 19.13,
    price_after_discount: 13.96,
    expiration_date: "2025-01-26",
    category: "water and drinks",
  },
];
const lidlSuggestedCoupons = [
  {
    name: "Nestl\u00e9 Fitness 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Lidl",
    price_before_discount: 6.06,
    price_after_discount: 3.94,
    expiration_date: "2025-02-14",
    category: "dry products",
  },
  {
    name: "Free-range eggs 10 pcs",
    manufacturer: "Fermy Drobiu Woźniak",
    store: "Lidl",
    price_before_discount: 9.99,
    price_after_discount: 8.69,
    expiration_date: "2024-12-12",
    category: "Dairy Products",
  },
  {
    name: "Free-range eggs 10 pcs",
    manufacturer: "Fermy Drobiu Woźniak",
    store: "Lidl",
    price_before_discount: 9.99,
    price_after_discount: 8.69,
    expiration_date: "2024-12-12",
    category: "dry products",
  },
];
const biedronkaAllCoupons = [
  {
    name: "Oasis Orange Juice 500g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 8.74,
    price_after_discount: 7.52,
    expiration_date: "2025-01-14",
    category: "water and drinks",
  },
  {
    name: "Milka Chocolate Bar 250g",
    manufacturer: "Mondelez",
    store: "Biedronka",
    price_before_discount: 14.67,
    price_after_discount: 10.27,
    expiration_date: "2025-01-28",
    category: "snacks and sweets",
  },
  {
    name: "Nescaf\u00e9 Classic 120g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 3.15,
    price_after_discount: 1.8,
    expiration_date: "2025-02-16",
    category: "water and drinks",
  },
  {
    name: "Milka Chocolate Bar 500g",
    manufacturer: "Mondelez",
    store: "Biedronka",
    price_before_discount: 15.35,
    price_after_discount: 9.06,
    expiration_date: "2025-01-28",
    category: "snacks and sweets",
  },
  {
    name: "Cheetos Puffs 1000g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 14.84,
    price_after_discount: 11.87,
    expiration_date: "2025-02-09",
    category: "snacks and sweets",
  },
  {
    name: "Lay's Classic Chips 1000g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 5.16,
    price_after_discount: 3.66,
    expiration_date: "2025-01-31",
    category: "snacks and sweets",
  },
  {
    name: "Milka Chocolate Bar 1000g",
    manufacturer: "Mondelez",
    store: "Biedronka",
    price_before_discount: 3.08,
    price_after_discount: 1.85,
    expiration_date: "2025-01-29",
    category: "snacks and sweets",
  },
  {
    name: "Lay's Classic Chips 120g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 12.6,
    price_after_discount: 6.55,
    expiration_date: "2025-02-13",
    category: "snacks and sweets",
  },
  {
    name: "Nestl\u00e9 Fitness 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 7.27,
    price_after_discount: 6.18,
    expiration_date: "2025-02-14",
    category: "dry products",
  },
  {
    name: "Oasis Orange Juice 1000g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 19.68,
    price_after_discount: 17.52,
    expiration_date: "2025-01-29",
    category: "water and drinks",
  },
  {
    name: "Cheetos Puffs 120g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 10.01,
    price_after_discount: 6.31,
    expiration_date: "2025-02-06",
    category: "snacks and sweets",
  },
  {
    name: "Milka Chocolate Bar 120g",
    manufacturer: "Mondelez",
    store: "Biedronka",
    price_before_discount: 3.18,
    price_after_discount: 2.48,
    expiration_date: "2025-01-27",
    category: "snacks and sweets",
  },
  {
    name: "Rama Margarine 120g",
    manufacturer: "Upfield",
    store: "Biedronka",
    price_before_discount: 7.42,
    price_after_discount: 3.86,
    expiration_date: "2025-01-29",
    category: "dairy products",
  },
  {
    name: "Oasis Orange Juice 120g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 18.48,
    price_after_discount: 13.86,
    expiration_date: "2025-01-08",
    category: "water and drinks",
  },
  {
    name: "Lipton Yellow Label Tea 250g",
    manufacturer: "Unilever",
    store: "Biedronka",
    price_before_discount: 8.01,
    price_after_discount: 6.01,
    expiration_date: "2025-01-12",
    category: "water and drinks",
  },
  {
    name: "Rama Margarine 250g",
    manufacturer: "Upfield",
    store: "Biedronka",
    price_before_discount: 9.3,
    price_after_discount: 7.25,
    expiration_date: "2025-01-11",
    category: "dairy products",
  },
  {
    name: "Activia Yogurt 500g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 16.68,
    price_after_discount: 13.84,
    expiration_date: "2025-01-12",
    category: "dairy products",
  },
  {
    name: "Heinz Tomato Ketchup 1000g",
    manufacturer: "Heinz",
    store: "Biedronka",
    price_before_discount: 4.24,
    price_after_discount: 2.97,
    expiration_date: "2025-01-05",
    category: "spices and seasonings",
  },
  {
    name: "Cheetos Puffs 500g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 14.8,
    price_after_discount: 8.88,
    expiration_date: "2025-01-01",
    category: "snacks and sweets",
  },
  {
    name: "Rama Margarine 1000g",
    manufacturer: "Upfield",
    store: "Biedronka",
    price_before_discount: 4.66,
    price_after_discount: 3.96,
    expiration_date: "2025-01-17",
    category: "dairy products",
  },
  {
    name: "Oasis Orange Juice 250g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 3.63,
    price_after_discount: 2.65,
    expiration_date: "2025-02-03",
    category: "water and drinks",
  },
  {
    name: "Nescaf\u00e9 Classic 250g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 11.57,
    price_after_discount: 7.75,
    expiration_date: "2025-02-17",
    category: "water and drinks",
  },
  {
    name: "Activia Yogurt 1000g",
    manufacturer: "Danone",
    store: "Biedronka",
    price_before_discount: 11.14,
    price_after_discount: 8.47,
    expiration_date: "2025-01-12",
    category: "dairy products",
  },
  {
    name: "Lipton Yellow Label Tea 1000g",
    manufacturer: "Unilever",
    store: "Biedronka",
    price_before_discount: 4.7,
    price_after_discount: 3.43,
    expiration_date: "2025-01-21",
    category: "water and drinks",
  },
  {
    name: "Nescaf\u00e9 Classic 500g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 4.59,
    price_after_discount: 4.04,
    expiration_date: "2025-01-03",
    category: "water and drinks",
  },
  {
    name: "Nestl\u00e9 Fitness 250g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 6.1,
    price_after_discount: 5.31,
    expiration_date: "2025-02-13",
    category: "dry products",
  },
  {
    name: "Nestl\u00e9 Fitness 120g",
    manufacturer: "Nestl\u00e9",
    store: "Biedronka",
    price_before_discount: 4.59,
    price_after_discount: 3.3,
    expiration_date: "2025-01-08",
    category: "dry products",
  },
  {
    name: "Lay's Classic Chips 250g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 14.7,
    price_after_discount: 11.91,
    expiration_date: "2025-01-13",
    category: "snacks and sweets",
  },
  {
    name: "Lay's Classic Chips 500g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 18.0,
    price_after_discount: 10.8,
    expiration_date: "2025-01-06",
    category: "snacks and sweets",
  },
  {
    name: "Cheetos Puffs 250g",
    manufacturer: "Frito-Lay",
    store: "Biedronka",
    price_before_discount: 3.04,
    price_after_discount: 1.95,
    expiration_date: "2025-01-16",
    category: "snacks and sweets",
  },
  {
    name: "Heinz Tomato Ketchup 120g",
    manufacturer: "Heinz",
    store: "Biedronka",
    price_before_discount: 12.95,
    price_after_discount: 10.36,
    expiration_date: "2025-01-06",
    category: "spices and seasonings",
  },
];
const biedronkaSuggestedCoupons = [];
const carrefourAllCoupons = [
  {
    name: "Rama Margarine 120g",
    manufacturer: "Upfield",
    store: "Carrefour",
    price_before_discount: 6.74,
    price_after_discount: 3.84,
    expiration_date: "2025-02-05",
    category: "dairy products",
  },
  {
    name: "Milka Chocolate Bar 250g",
    manufacturer: "Mondelez",
    store: "Carrefour",
    price_before_discount: 4.19,
    price_after_discount: 3.1,
    expiration_date: "2025-01-05",
    category: "snacks and sweets",
  },
  {
    name: "Oasis Orange Juice 1000g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 4.91,
    price_after_discount: 3.39,
    expiration_date: "2025-01-15",
    category: "water and drinks",
  },
  {
    name: "Rama Margarine 250g",
    manufacturer: "Upfield",
    store: "Carrefour",
    price_before_discount: 17.27,
    price_after_discount: 9.67,
    expiration_date: "2025-01-11",
    category: "dairy products",
  },
  {
    name: "Lipton Yellow Label Tea 1000g",
    manufacturer: "Unilever",
    store: "Carrefour",
    price_before_discount: 11.0,
    price_after_discount: 8.58,
    expiration_date: "2025-02-11",
    category: "water and drinks",
  },
  {
    name: "Nescaf\u00e9 Classic 500g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 19.31,
    price_after_discount: 13.13,
    expiration_date: "2025-02-02",
    category: "water and drinks",
  },
  {
    name: "Lay's Classic Chips 500g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 3.22,
    price_after_discount: 1.87,
    expiration_date: "2025-02-08",
    category: "snacks and sweets",
  },
  {
    name: "Lipton Yellow Label Tea 500g",
    manufacturer: "Unilever",
    store: "Carrefour",
    price_before_discount: 4.78,
    price_after_discount: 2.68,
    expiration_date: "2025-02-02",
    category: "water and drinks",
  },
  {
    name: "Lay's Classic Chips 1000g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 14.26,
    price_after_discount: 12.69,
    expiration_date: "2025-01-15",
    category: "snacks and sweets",
  },
  {
    name: "Lipton Yellow Label Tea 120g",
    manufacturer: "Unilever",
    store: "Carrefour",
    price_before_discount: 18.47,
    price_after_discount: 12.19,
    expiration_date: "2025-01-03",
    category: "water and drinks",
  },
  {
    name: "Nestl\u00e9 Fitness 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 5.62,
    price_after_discount: 4.1,
    expiration_date: "2025-01-16",
    category: "dry products",
  },
  {
    name: "Cheetos Puffs 120g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 13.53,
    price_after_discount: 8.12,
    expiration_date: "2025-01-12",
    category: "snacks and sweets",
  },
  {
    name: "Rama Margarine 1000g",
    manufacturer: "Upfield",
    store: "Carrefour",
    price_before_discount: 8.93,
    price_after_discount: 7.59,
    expiration_date: "2025-01-01",
    category: "dairy products",
  },
  {
    name: "Nestl\u00e9 Fitness 250g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 6.01,
    price_after_discount: 4.81,
    expiration_date: "2025-01-31",
    category: "dry products",
  },
  {
    name: "Oasis Orange Juice 250g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 3.31,
    price_after_discount: 2.71,
    expiration_date: "2025-01-17",
    category: "water and drinks",
  },
  {
    name: "Cheetos Puffs 500g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 14.32,
    price_after_discount: 12.74,
    expiration_date: "2025-02-10",
    category: "snacks and sweets",
  },
  {
    name: "Heinz Tomato Ketchup 250g",
    manufacturer: "Heinz",
    store: "Carrefour",
    price_before_discount: 4.74,
    price_after_discount: 3.98,
    expiration_date: "2025-01-09",
    category: "spices and seasonings",
  },
  {
    name: "Cheetos Puffs 250g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 4.89,
    price_after_discount: 3.96,
    expiration_date: "2025-02-08",
    category: "snacks and sweets",
  },
  {
    name: "Activia Yogurt 1000g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 5.09,
    price_after_discount: 2.9,
    expiration_date: "2025-02-13",
    category: "dairy products",
  },
  {
    name: "Nescaf\u00e9 Classic 1000g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 8.24,
    price_after_discount: 4.78,
    expiration_date: "2025-01-22",
    category: "water and drinks",
  },
  {
    name: "Milka Chocolate Bar 500g",
    manufacturer: "Mondelez",
    store: "Carrefour",
    price_before_discount: 10.49,
    price_after_discount: 5.98,
    expiration_date: "2025-02-09",
    category: "snacks and sweets",
  },
  {
    name: "Cheetos Puffs 1000g",
    manufacturer: "Frito-Lay",
    store: "Carrefour",
    price_before_discount: 9.04,
    price_after_discount: 6.87,
    expiration_date: "2025-01-24",
    category: "snacks and sweets",
  },
  {
    name: "Oasis Orange Juice 500g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 13.52,
    price_after_discount: 10.41,
    expiration_date: "2025-02-01",
    category: "water and drinks",
  },
  {
    name: "Milka Chocolate Bar 1000g",
    manufacturer: "Mondelez",
    store: "Carrefour",
    price_before_discount: 6.19,
    price_after_discount: 4.27,
    expiration_date: "2025-02-09",
    category: "snacks and sweets",
  },
  {
    name: "Activia Yogurt 120g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 13.8,
    price_after_discount: 8.0,
    expiration_date: "2025-02-03",
    category: "dairy products",
  },
  {
    name: "Milka Chocolate Bar 120g",
    manufacturer: "Mondelez",
    store: "Carrefour",
    price_before_discount: 9.96,
    price_after_discount: 8.27,
    expiration_date: "2025-01-31",
    category: "snacks and sweets",
  },
  {
    name: "Rama Margarine 500g",
    manufacturer: "Upfield",
    store: "Carrefour",
    price_before_discount: 7.82,
    price_after_discount: 3.99,
    expiration_date: "2025-02-01",
    category: "dairy products",
  },
  {
    name: "Oasis Orange Juice 120g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 15.79,
    price_after_discount: 14.21,
    expiration_date: "2025-02-16",
    category: "water and drinks",
  },
  {
    name: "Nescaf\u00e9 Classic 120g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 9.83,
    price_after_discount: 7.08,
    expiration_date: "2025-01-20",
    category: "water and drinks",
  },
  {
    name: "Nestl\u00e9 Fitness 120g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 7.49,
    price_after_discount: 5.24,
    expiration_date: "2025-02-09",
    category: "dry products",
  },
  {
    name: "Heinz Tomato Ketchup 500g",
    manufacturer: "Heinz",
    store: "Carrefour",
    price_before_discount: 19.01,
    price_after_discount: 16.54,
    expiration_date: "2025-02-16",
    category: "spices and seasonings",
  },
  {
    name: "Activia Yogurt 250g",
    manufacturer: "Danone",
    store: "Carrefour",
    price_before_discount: 19.62,
    price_after_discount: 15.3,
    expiration_date: "2025-01-12",
    category: "dairy products",
  },
  {
    name: "Nescaf\u00e9 Classic 250g",
    manufacturer: "Nestl\u00e9",
    store: "Carrefour",
    price_before_discount: 7.92,
    price_after_discount: 5.15,
    expiration_date: "2025-01-04",
    category: "water and drinks",
  },
  {
    name: "Heinz Tomato Ketchup 120g",
    manufacturer: "Heinz",
    store: "Carrefour",
    price_before_discount: 4.87,
    price_after_discount: 3.41,
    expiration_date: "2025-02-01",
    category: "spices and seasonings",
  },
  {
    name: "Heinz Tomato Ketchup 1000g",
    manufacturer: "Heinz",
    store: "Carrefour",
    price_before_discount: 6.77,
    price_after_discount: 3.59,
    expiration_date: "2025-01-03",
    category: "spices and seasonings",
  },
  {
    name: "Lipton Yellow Label Tea 250g",
    manufacturer: "Unilever",
    store: "Carrefour",
    price_before_discount: 15.1,
    price_after_discount: 11.17,
    expiration_date: "2025-02-01",
    category: "water and drinks",
  },
];
const carrefourSuggestedCoupons = [];

const Shops = (props) => {
  const { shoppingListId } = props;
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const [selectedShopAllCoupons, setSelectedShopAllCoupons] = useState(null);
  const [selectedShopSugestedCoupons, setSelectedShopSugestedCoupons] =
    useState(null);
  const showDialog = (shopName) => {
    if (shopName === "Lidl") {
      setIsDialogOpen(true);
      setSelectedShopAllCoupons(lidlAllCoupons);
      setSelectedShopSugestedCoupons(lidlSuggestedCoupons);
    } else if (shopName === "Biedronka") {
      setIsDialogOpen(true);
      setSelectedShopAllCoupons(biedronkaAllCoupons);
      setSelectedShopSugestedCoupons(biedronkaSuggestedCoupons);
    } else {
      setIsDialogOpen(true);
      setSelectedShopAllCoupons(carrefourAllCoupons);
      setSelectedShopSugestedCoupons(carrefourSuggestedCoupons);
    }
  };
  return (
    <>
      {isDialogOpen && (
        <DialogCoupons
          suggestedCoupons={selectedShopSugestedCoupons}
          allCoupons={selectedShopAllCoupons}
          isDialogOpen={isDialogOpen}
          handleClose={() => setIsDialogOpen(false)}
          shoppingListId={shoppingListId}
        />
      )}
      <div className="shops-wrapper">
        <div className="shops-container">
          <Shop
            name="Lidl"
            couponsAmount={lidlSuggestedCoupons.length}
            showDialog={showDialog}
          />
          <Shop
            name="Biedronka"
            couponsAmount={biedronkaSuggestedCoupons.length}
            showDialog={showDialog}
          />
          <Shop
            name="Carrefour"
            couponsAmount={carrefourSuggestedCoupons.length}
            showDialog={showDialog}
          />
        </div>
      </div>
    </>
  );
};
export default Shops;
